version: '3.8'

services:
  app:
    build:
      context: .
    container_name: phx_app
    ports:
      - "4000:4000"
    environment:
      - MIX_ENV=dev
      - DATABASE_URL=ecto://postgres:postgres@db/postgres
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    command: sh -c "mix deps.get && mix phx.server"

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5434"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
