services:
  app:
    build:
      context: .
    container_name: phx_app
    ports:
      - "4000:4000"
    environment:
      - MIX_ENV=dev
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/app
    depends_on:
      - redis
    command: sh -c "mix deps.get && mix phx.server"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
