services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - phx_network

volumes:
  redis_data:

networks:
  phx_network:
    driver: bridge